// pages/home/home.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    items:[
      {
        title:"影院热映",
        movies:[
          {
            icon:"",
            title:"我和我的祖国",
            score:8.0
          },
          {
            icon:"",
            title:"中国机长",
            score:7.0
          },
          {
            icon:"",
            title:"犯罪现场",
            desc:"尚未上映"
          },
          {
            icon:"",
            title:"极速逃脱",
            score:6.2
          },
        ]
      },
      {
        title:"豆瓣热门",
        movies:[
          {
            icon:"",
            title:"银河补习班",
            score:6.2
          },
          {
            icon:"",
            title:"安娜",
            score:7.7
          },
          {
            icon:"",
            title:"我的天使",
            score:6.6
          },
          {
            icon:"",
            title:"保持沉默",
            score:5.2
          },
        ]
      },
      {
        title:"近期热门剧集",
        movies:[
          {
            icon:"",
            title:"致命女人",
            score:9.3
          },
          {
            icon:"",
            title:"我在未来等你",
            score:8.1
          },
          {
            icon:"",
            title:"他人即地狱",
            score:8.4
          },
          {
            icon:"",
            title:"真相捕捉 第一季",
            score:9.1
          },
        ]
      }
    ]
  },
})